### ISSUE TITLE
Import-Csv : Element <nn> already exists

### ISSUE THREAD

**Issue by drohnen** [soteria-security/HAFNIUM-IOC#2]
When I run the script, I get many error messages with the following text:

Import-Csv : Das Element "21" ist bereits vorhanden.
In C:\users\<username>\HAFNIUM-Exchange-IOC.ps1:62 Zeichen:26
+       $CVE_2021_26855 += Import-Csv -Path $log.FullName | Where-Objec ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Csv], ExtendedTypeSystemException
    + FullyQualifiedErrorId : AlreadyPresentPSMemberInfoInternalCollectionAdd,Microsoft.PowerShell.Commands.ImportCsvCommand

Is there any troubleshooting or a tip on what I can do about this?

Thank you in advance and best regards

Matze

**Comment by poolebc-soteria** [comment]
Sounds like the CSV log has a duplicate header. Is there any way you can run the following and share the results?

```
$myLogs = Get-ChildItem -Recurse -Path "$env:ExchangeInstallPath\V15\Logging\HttpProxy" -Filter '*.log' -ErrorAction SilentlyContinue; foreach ($log in $Mylogs) {Get-Content $log.FullName  | select -First 1}
```
